### ISSUE TITLE
Lambda, Thumbnail maker

### ISSUE THREAD

**Issue by ecsimsw** [ecsimsw/pic-up#26]
### 문제

WAS에서 썸네일을 직접 만드는 것이 아닌, 썸네일을 따로 처리하는 람다를 만들 생각이다.
1. 리사이징 하는데 시간이 오래걸렸고, (1mb, 100개 동시 요청, 평균 500ms)
2. 메모리가 사용되어 동시 업로드 요청이 발생했을 때 메모리가 급등했다가 GC로 바로 제거되는 등, 메모리 급변 문제가 있었다.

### Todos
- [x] S3 upload event 를 트리거로 동작하는 Lambda 생성
- [x] 썸네일 필요 여부 확인 -> 이미지 파일 리사이징 -> S3에 저장
- [x] 썸네일이 제작되고 S3에 저장되는 시간 간격 처리
- [x] 썸네일 제작 실패시 처리
- [ ] Terraform으로 IaC

### 썸네일이 제작되고 S3에 저장되는 시간 간격 처리 고민
X. WAS에서 CDN URL을 전달할 때, 생성된지 N초가 안된 사진 데이터는 원본 사진 사용
2. 썸네일 제작이 완료되면 람다 -> WAS, 썸네일 생성 및 저장이 완료됨을 알림. 그 전까진 원본 사진 사용
3. 동영상은 썸네일 제작 때까지 임시 파일 사용

### 썸네일 제작 실패시 처리
1. WAS에 알리고 WAS에서 직접 썸네일 파일 생성 및 S3 업로드 -> 그래도 실패한다면 그냥 원본 사진으로 사용

**Comment by ecsimsw** [comment]
Java17
사진 리사이징, 동영상 프레임 캡쳐
썸네일 처리 완료 BE 전달

`https://github.com/ecsimsw/pic-up/blob/main/lambda-thumbnail/src/main/java/ecsimsw/picup/ThumbnailMaker.java`
